-- Tables already created manually in Supabase:
-- affiliates (id, user_id, code, commission_rate, total_earned, total_paid, created_at)
-- affiliate_referrals (id, affiliate_user_id, referred_user_id, challenge_id, purchase_amount, commission_amount, status, created_at)
-- No migration needed.
